name: digging
description: digging
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^3.0.1
  convert: ^3.0.0
  pointycastle: ^3.4.0
  cupertino_icons: ^1.0.2
  bip39: ^1.0.6
  bip32: ^2.0.0
  fluttertoast: ^8.0.8
  path_provider: ^2.0.9
  pull_to_refresh: ^2.0.0
  get: ^4.6.1
  flutter_native_splash: ^2.1.0
  shared_preferences: ^2.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - images/

flutter_native_splash:
  color: "#ffffff"
  image: images/splash4.png